# Generated by Django 2.1.1 on 2018-09-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20180928_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='end_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
