# Generated by Django 2.1.2 on 2018-10-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20180928_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
