# Generated by Django 2.1.2 on 2018-10-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_doctor_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='owner',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='owner',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='owner',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='owner',
            new_name='treatment',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='owner',
            new_name='patient',
        ),
    ]
